mapzen/on-the-road_android

src/main/java/com/mapzen/valhalla/Instruction.java
src/main/java/com/mapzen/valhalla/Node.java
src/main/java/com/mapzen/valhalla/Route.java
src/main/java/com/mapzen/valhalla/Router.java
src/test/java/com/mapzen/valhalla/InstructionTest.java
src/test/java/com/mapzen/valhalla/RouteTest.java
src/test/java/com/mapzen/valhalla/RouterTest.java

* Duplicates OSRM package and classes for Valhalla
* Modifies base URL and query params
TODO: Parse Valhalla response format and update data structures.

Adds support for Valhalla routing service

---

build.gradle
circle.yml
gradle-mvn-push.gradle
gradle.properties

`$ ./gradlew clean uploadArchvies`

Adds deployment to sonatype snapshots repo

---

build.gradle
src/main/java/com/mapzen/valhalla/Route.kt
src/test/java/com/mapzen/valhalla/InstructionTest.java
src/test/java/com/mapzen/valhalla/RouteTest.java

- Removes skip for continue on
- Removes tests involving skipping

stops skipping continue ons and ups version

---

build.gradle
src/test/java/com/mapzen/valhalla/RouterTest.java

- Upgrades to okhttp 2.4 and retrofit 1.0

updates okhttp and retrofit

---

src/main/java/com/mapzen/helpers/RouteEngine.java
src/main/java/com/mapzen/valhalla/Route.kt
src/test/java/com/mapzen/helpers/RouteEngineTest.java
src/test/java/com/mapzen/valhalla/RouteTest.java

Removes JSON exceptions from Route method signatures

Adds RouteEngine utility for in-route navigation

---

src/main/java/com/mapzen/helpers/RouteEngine.java
src/main/java/com/mapzen/valhalla/Instruction.kt
src/main/java/com/mapzen/valhalla/Node.kt
src/main/java/com/mapzen/valhalla/Route.kt
src/main/java/com/mapzen/valhalla/RouteCallback.kt
src/main/java/com/mapzen/valhalla/Router.kt
src/main/java/com/mapzen/valhalla/RoutingService.java
src/main/java/com/mapzen/valhalla/ValhallaRouter.kt
src/test/fixtures/street_not_found_valhalla
src/test/java/com/mapzen/valhalla/InstructionTest.java
src/test/java/com/mapzen/valhalla/RouterTest.java

Currently calling `Instruction#getName()` when none are specified in the JSON throws an exception. This checks to see if `"street_names"` are present and if not returns the `"instruction"` text.

Return instruction text when no street names

---

build.gradle
src/main/java/com/mapzen/helpers/RouteEngine.java
src/main/java/com/mapzen/helpers/RouteListener.java
src/main/java/com/mapzen/valhalla/Instruction.kt
src/main/java/com/mapzen/valhalla/Route.kt
src/test/java/com/mapzen/helpers/RouteEngineTest.java

* Adds separate route engine callbacks for approach and alert.
* Notifies listener at one mile and 1/4 mile when approaching instruction maneuver.
* Upgrades Android Gradle plugin.
TODO: Add support for metric (km) approach milestones checks.

Adds new route engine callbacks that can be used for voice navigation.

---

src/main/java/com/mapzen/valhalla/JSON.java
src/main/java/com/mapzen/valhalla/Router.kt
src/main/java/com/mapzen/valhalla/ValhallaRouter.kt
src/test/java/com/mapzen/valhalla/RouterTest.java

Set distance units in route request

---

src/main/java/com/mapzen/helpers/DistanceFormatter.java
src/main/java/com/mapzen/valhalla/Instruction.kt
src/main/java/com/mapzen/valhalla/Route.kt
src/test/fixtures/brooklyn_valhalla_miles.route
src/test/java/com/mapzen/helpers/DistanceFormatterConfigTest.java
src/test/java/com/mapzen/helpers/DistanceFormatterMetersTest.java
src/test/java/com/mapzen/valhalla/InstructionTest.java
src/test/java/com/mapzen/valhalla/RouteTest.java

Instead of relying on the system default locale to determine output distance units these can now be specified in a parameter.

Adds ability to configure DistanceFormatter using locale or distance units

---

build.gradle

Kotlin 0.13.1514

---

build.gradle
src/main/java/com/mapzen/helpers/CharStreams.java
src/main/java/com/mapzen/valhalla/ValhallaRouter.kt

* Make Guava and MockWebServer test only dependencies
* Copy relevant portions of Guava into `com.mapzen.helers.CharStreams`
* Update compile and target SDK version

Reduce library method count

---

build.gradle

Fixes DEXOPT error on app install.
https://devnet.jetbrains.com/message/5561799#5561799

Kotlin 1.0.0-beta-1103

---

src/main/java/com/mapzen/valhalla/Router.kt
src/main/java/com/mapzen/valhalla/ValhallaRouter.kt
src/test/java/com/mapzen/valhalla/RouterTest.java

Enabled by default with the option to disable it anytime
Closes #428

Send DNT header to disable server-side logging

---

gradle-mvn-push.gradle
gradle.properties

* Update Gradle script to deploy release version to Maven Central.
* Exclude Kotlin files in Javadoc prep.
* Update version number to deploy 0.8.

Deploy release

---

src/main/java/com/mapzen/valhalla/Route.kt
src/test/java/com/mapzen/valhalla/RouteTest.java

- Breaks code into smaller functions for readability
- Adds logic to better handle constant reroute by saying if we havent started route and arent close to another section of route, dont consider user lost
Closes https://github.com/mapzen/eraser-map/issues/334

Unending reroute improvement

---

src/main/java/com/mapzen/valhalla/Router.kt
src/main/java/com/mapzen/valhalla/ValhallaRouter.kt
src/test/java/com/mapzen/valhalla/RouterTest.java

- Adds support for multimodal routing
Closes #74

Multimodal support

---

library/src/main/java/com/mapzen/valhalla/Instruction.kt
library/src/main/java/com/mapzen/valhalla/TransitInfo.kt
library/src/main/java/com/mapzen/valhalla/TransitStop.kt
library/src/main/java/com/mapzen/valhalla/TravelMode.kt
library/src/main/java/com/mapzen/valhalla/TravelType.kt
library/src/test/fixtures/json_valhalla.instruction
library/src/test/fixtures/json_valhalla.transitinfo
library/src/test/fixtures/json_valhalla.transitstop
library/src/test/java/com/mapzen/TestUtils.java
library/src/test/java/com/mapzen/valhalla/HttpHandlerTest.java
library/src/test/java/com/mapzen/valhalla/InstructionTest.java
library/src/test/java/com/mapzen/valhalla/RouteTest.java
library/src/test/java/com/mapzen/valhalla/RouterTest.java
library/src/test/java/com/mapzen/valhalla/TransitInfoTest.java
library/src/test/java/com/mapzen/valhalla/TransitStopTest.java

- Expose `travel_type`, `travel_mode`, and `transit_info`
- Handle optional properties

Expose transit properties

---

library/src/main/java/com/mapzen/valhalla/JSON.java
library/src/main/java/com/mapzen/valhalla/Router.kt
library/src/main/java/com/mapzen/valhalla/ValhallaRouter.kt
library/src/test/java/com/mapzen/valhalla/RouterTest.java
sample/src/main/java/com/mapzen/turnbyturn/sample/MainActivity.java
sample/src/main/res/layout-land/activity_main.xml
sample/src/main/res/layout-port/activity_main.xml
sample/src/main/res/values/strings.xml

- Allow setting router language
- Add language to direction options
- Update tests to ensure language properly set
- Update sample app to allow configuring language
Closes #89

Set Router Language

---

sample/build.gradle
sample/src/main/java/com/mapzen/turnbyturn/sample/SampleHttpHandler.java

- Updates name of gradle property read to be more generic
- Updates corresponding build config field to also be more generic for unified api key

Unified api key

---

library/src/main/java/com/mapzen/valhalla/Router.kt
library/src/test/java/com/mapzen/valhalla/RouterTest.java
sample/src/main/res/values/strings.xml

we now have russian thanks to @krava2008

alphabetize and add russian

---

README.md

Add sample app api key instructions to README
